"""
Language definitions for PDF Editor Pro
Supports: English, Arabic, Russian, Chinese, Spanish, French, German, Japanese, Korean, Portuguese
"""

LANGUAGES = {
    "en": {
        "name": "English",
        "dir": "ltr",
        "app_title": "PDF Editor Pro",
        "file": "File",
        "edit": "Edit",
        "page": "Page",
        "insert": "Insert",
        "view": "View",
        "tools": "Tools",
        "help": "Help",
        "language": "Language",
        "open": "Open",
        "save": "Save",
        "save_as": "Save As",
        "export_images": "Export as Images",
        "extract_text": "Extract Text",
        "exit": "Exit",
        "undo": "Undo",
        "redo": "Redo",
        "copy": "Copy",
        "paste": "Paste",
        "delete": "Delete",
        "find_replace": "Find & Replace",
        "add_page": "Add Page",
        "delete_page": "Delete Page",
        "rotate_page": "Rotate Page",
        "extract_pages": "Extract Pages",
        "merge_pdf": "Merge PDFs",
        "text": "Text",
        "image": "Image",
        "comment": "Comment",
        "link": "Link",
        "signature": "Signature",
        "stamp": "Stamp",
        "watermark": "Watermark",
        "zoom_in": "Zoom In",
        "zoom_out": "Zoom Out",
        "actual_size": "Actual Size",
        "shortcuts": "Keyboard Shortcuts",
        "about": "About",
        "select": "Select",
        "highlight": "Highlight",
        "underline": "Underline",
        "strikeout": "Strikeout",
        "rectangle": "Rectangle",
        "circle": "Circle",
        "line": "Line",
        "arrow": "Arrow",
        "freehand": "Freehand",
        "eraser": "Eraser",
        "pages": "Pages",
        "properties": "Properties",
        "size": "Size",
        "color": "Color",
        "font": "Font",
        "thickness": "Thickness",
        "apply": "Apply",
        "cancel": "Cancel",
        "ready": "Ready",
        "tool": "Tool",
        "no_file": "No file open",
        "unsaved_changes": "There are unsaved changes. Save?",
        "save_changes": "Save Changes",
        "success": "Success",
        "error": "Error",
        "confirm": "Confirm",
        "page_of": "of",
        "edit_text": "Edit Text",
        "new_text": "New Text",
        "enter_text": "Enter text:",
        "find": "Find:",
        "replace_with": "Replace with:",
        "replace_all": "Replace All",
        "no_match": "No matches found",
        "matches_replaced": "matches replaced",
        "image_tools": "Image Tools",
        "select_image": "Select Image",
        "move_image": "Move Image",
        "resize_image": "Resize Image",
        "scale_image": "Scale Image",
        "rotate_image": "Rotate Image",
        "delete_image": "Delete Image",
        "replace_image": "Replace Image",
        "extract_image": "Extract Image",
        "images": "Images",
        "no_images": "No images on this page",
        "image_deleted": "Image deleted",
        "image_replaced": "Image replaced",
        "image_moved": "Image moved",
        "select_image_first": "Select an image first",
        "draft": "DRAFT",
        "confidential": "CONFIDENTIAL",
        "final": "FINAL",
        "rejected": "REJECTED",
        "approved": "APPROVED",
        "urgent": "URGENT",
        "draw_signature": "Draw your signature",
        "clear": "Clear",
        "insert_sig": "Insert",
        "choose_stamp": "Choose Stamp",
        "enter_watermark": "Enter watermark text:",
        "total_pages": "Total pages",
        "enter_page_range": "Enter page range (e.g., 1,3,5-8):",
        "extract": "Extract",
        "split": "Split",
        "merge": "Merge",
        "rotation_degree": "Rotation degree:",
        "rotate": "Rotate",
        "file_saved": "File saved",
        "file_opened": "File opened",
        "changes_applied": "Changes applied",
        "editing_cancelled": "Editing cancelled",
        "layers": "Layers",
        "auto_saved": "Auto-saved",
        "recovery_found": "Recovery file found. Restore?",
        "memory_usage": "Memory usage",
    },
    "ar": {
        "name": "العربية",
        "dir": "rtl",
        "app_title": "محرر PDF احترافي",
        "file": "ملف",
        "edit": "تحرير",
        "page": "صفحة",
        "insert": "إدراج",
        "view": "عرض",
        "tools": "أدوات",
        "help": "مساعدة",
        "language": "اللغة",
        "open": "فتح",
        "save": "حفظ",
        "save_as": "حفظ باسم",
        "export_images": "تصدير كصور",
        "extract_text": "استخراج النص",
        "exit": "خروج",
        "undo": "تراجع",
        "redo": "إعادة",
        "copy": "نسخ",
        "paste": "لصق",
        "delete": "حذف",
        "find_replace": "بحث واستبدال",
        "add_page": "إضافة صفحة",
        "delete_page": "حذف صفحة",
        "rotate_page": "تدوير الصفحة",
        "extract_pages": "استخراج صفحات",
        "merge_pdf": "دمج PDF",
        "text": "نص",
        "image": "صورة",
        "comment": "تعليق",
        "link": "رابط",
        "signature": "توقيع",
        "stamp": "ختم",
        "watermark": "علامة مائية",
        "zoom_in": "تكبير",
        "zoom_out": "تصغير",
        "actual_size": "حجم فعلي",
        "shortcuts": "اختصارات لوحة المفاتيح",
        "about": "حول البرنامج",
        "select": "تحديد",
        "highlight": "تظليل",
        "underline": "تسطير",
        "strikeout": "شطب",
        "rectangle": "مستطيل",
        "circle": "دائرة",
        "line": "خط",
        "arrow": "سهم",
        "freehand": "رسم حر",
        "eraser": "ممحاة",
        "pages": "الصفحات",
        "properties": "الخصائص",
        "size": "الحجم",
        "color": "اللون",
        "font": "الخط",
        "thickness": "السمك",
        "apply": "تطبيق",
        "cancel": "إلغاء",
        "ready": "جاهز",
        "tool": "أداة",
        "no_file": "لا يوجد ملف مفتوح",
        "unsaved_changes": "هناك تغييرات غير محفوظة. هل تريد الحفظ؟",
        "save_changes": "حفظ التغييرات",
        "success": "نجاح",
        "error": "خطأ",
        "confirm": "تأكيد",
        "page_of": "من",
        "edit_text": "تحرير النص",
        "new_text": "نص جديد",
        "enter_text": "أدخل النص:",
        "find": "بحث عن:",
        "replace_with": "استبدال بـ:",
        "replace_all": "استبدال الكل",
        "no_match": "لم يتم العثور على النص",
        "matches_replaced": "تم استبدال",
        "image_tools": "أدوات الصور",
        "select_image": "تحديد صورة",
        "move_image": "نقل صورة",
        "resize_image": "تغيير حجم",
        "delete_image": "حذف صورة",
        "replace_image": "استبدال صورة",
        "extract_image": "استخراج صورة",
        "images": "الصور",
        "no_images": "لا توجد صور في هذه الصفحة",
        "image_deleted": "تم حذف الصورة",
        "image_replaced": "تم استبدال الصورة",
        "image_moved": "تم نقل الصورة",
        "select_image_first": "اختر صورة أولاً",
        "draft": "مسودة",
        "confidential": "سري",
        "final": "نهائي",
        "rejected": "مرفوض",
        "approved": "موافق",
        "urgent": "عاجل",
        "draw_signature": "ارسم توقيعك",
        "clear": "مسح",
        "insert_sig": "إدراج",
        "choose_stamp": "اختر ختم",
        "enter_watermark": "أدخل نص العلامة المائية:",
        "total_pages": "إجمالي الصفحات",
        "enter_page_range": "أدخل نطاق الصفحات (مثال: 1,3,5-8):",
        "extract": "استخراج",
        "split": "تقسيم",
        "merge": "دمج",
        "rotation_degree": "درجة التدوير:",
        "rotate": "تدوير",
        "file_saved": "تم حفظ الملف",
        "file_opened": "تم فتح الملف",
        "changes_applied": "تم تطبيق التغييرات",
        "editing_cancelled": "تم إلغاء التحرير",
        "layers": "الطبقات",
        "auto_saved": "تم الحفظ التلقائي",
        "recovery_found": "تم العثور على ملف استرداد. هل تريد استعادته؟",
        "memory_usage": "استخدام الذاكرة",
    },
    "ru": {
        "name": "Русский",
        "dir": "ltr",
        "app_title": "PDF Редактор Pro",
        "file": "Файл",
        "edit": "Редактировать",
        "page": "Страница",
        "insert": "Вставка",
        "view": "Вид",
        "tools": "Инструменты",
        "help": "Справка",
        "language": "Язык",
        "open": "Открыть",
        "save": "Сохранить",
        "save_as": "Сохранить как",
        "export_images": "Экспорт как изображения",
        "extract_text": "Извлечь текст",
        "exit": "Выход",
        "undo": "Отменить",
        "redo": "Повторить",
        "copy": "Копировать",
        "paste": "Вставить",
        "delete": "Удалить",
        "find_replace": "Найти и заменить",
        "add_page": "Добавить страницу",
        "delete_page": "Удалить страницу",
        "rotate_page": "Повернуть страницу",
        "extract_pages": "Извлечь страницы",
        "merge_pdf": "Объединить PDF",
        "text": "Текст",
        "image": "Изображение",
        "comment": "Комментарий",
        "link": "Ссылка",
        "signature": "Подпись",
        "stamp": "Штамп",
        "watermark": "Водяной знак",
        "zoom_in": "Увеличить",
        "zoom_out": "Уменьшить",
        "actual_size": "Реальный размер",
        "shortcuts": "Горячие клавиши",
        "about": "О программе",
        "select": "Выбрать",
        "highlight": "Выделить",
        "underline": "Подчеркнуть",
        "strikeout": "Зачеркнуть",
        "rectangle": "Прямоугольник",
        "circle": "Круг",
        "line": "Линия",
        "arrow": "Стрелка",
        "freehand": "Свободное рисование",
        "eraser": "Ластик",
        "pages": "Страницы",
        "properties": "Свойства",
        "size": "Размер",
        "color": "Цвет",
        "font": "Шрифт",
        "thickness": "Толщина",
        "apply": "Применить",
        "cancel": "Отмена",
        "ready": "Готово",
        "tool": "Инструмент",
        "no_file": "Файл не открыт",
        "unsaved_changes": "Есть несохранённые изменения. Сохранить?",
        "save_changes": "Сохранить изменения",
        "success": "Успешно",
        "error": "Ошибка",
        "confirm": "Подтвердить",
        "page_of": "из",
        "edit_text": "Редактировать текст",
        "new_text": "Новый текст",
        "enter_text": "Введите текст:",
        "find": "Найти:",
        "replace_with": "Заменить на:",
        "replace_all": "Заменить все",
        "no_match": "Совпадений не найдено",
        "matches_replaced": "заменено совпадений",
        "image_tools": "Инструменты изображений",
        "select_image": "Выбрать изображение",
        "move_image": "Переместить",
        "resize_image": "Изменить размер",
        "delete_image": "Удалить изображение",
        "replace_image": "Заменить изображение",
        "extract_image": "Извлечь изображение",
        "images": "Изображения",
        "no_images": "Нет изображений на странице",
        "image_deleted": "Изображение удалено",
        "image_replaced": "Изображение заменено",
        "image_moved": "Изображение перемещено",
        "select_image_first": "Сначала выберите изображение",
        "draft": "ЧЕРНОВИК",
        "confidential": "КОНФИДЕНЦИАЛЬНО",
        "final": "ФИНАЛ",
        "rejected": "ОТКЛОНЕНО",
        "approved": "ОДОБРЕНО",
        "urgent": "СРОЧНО",
        "draw_signature": "Нарисуйте подпись",
        "clear": "Очистить",
        "insert_sig": "Вставить",
        "choose_stamp": "Выберите штамп",
        "enter_watermark": "Введите текст водяного знака:",
        "total_pages": "Всего страниц",
        "enter_page_range": "Введите диапазон страниц (напр., 1,3,5-8):",
        "extract": "Извлечь",
        "split": "Разделить",
        "merge": "Объединить",
        "rotation_degree": "Угол поворота:",
        "rotate": "Повернуть",
        "file_saved": "Файл сохранён",
        "file_opened": "Файл открыт",
        "changes_applied": "Изменения применены",
        "editing_cancelled": "Редактирование отменено",
        "layers": "Слои",
        "auto_saved": "Автосохранение",
        "recovery_found": "Найден файл восстановления. Восстановить?",
        "memory_usage": "Использование памяти",
    },
    "zh": {
        "name": "中文",
        "dir": "ltr",
        "app_title": "PDF编辑器专业版",
        "file": "文件",
        "edit": "编辑",
        "page": "页面",
        "insert": "插入",
        "view": "视图",
        "tools": "工具",
        "help": "帮助",
        "language": "语言",
        "open": "打开",
        "save": "保存",
        "save_as": "另存为",
        "export_images": "导出为图片",
        "extract_text": "提取文本",
        "exit": "退出",
        "undo": "撤销",
        "redo": "重做",
        "copy": "复制",
        "paste": "粘贴",
        "delete": "删除",
        "find_replace": "查找和替换",
        "add_page": "添加页面",
        "delete_page": "删除页面",
        "rotate_page": "旋转页面",
        "extract_pages": "提取页面",
        "merge_pdf": "合并PDF",
        "text": "文本",
        "image": "图片",
        "comment": "评论",
        "link": "链接",
        "signature": "签名",
        "stamp": "印章",
        "watermark": "水印",
        "zoom_in": "放大",
        "zoom_out": "缩小",
        "actual_size": "实际大小",
        "shortcuts": "键盘快捷键",
        "about": "关于",
        "select": "选择",
        "highlight": "高亮",
        "underline": "下划线",
        "strikeout": "删除线",
        "rectangle": "矩形",
        "circle": "圆形",
        "line": "线条",
        "arrow": "箭头",
        "freehand": "自由绘制",
        "eraser": "橡皮擦",
        "pages": "页面",
        "properties": "属性",
        "size": "大小",
        "color": "颜色",
        "font": "字体",
        "thickness": "粗细",
        "apply": "应用",
        "cancel": "取消",
        "ready": "就绪",
        "tool": "工具",
        "no_file": "未打开文件",
        "unsaved_changes": "有未保存的更改。是否保存？",
        "save_changes": "保存更改",
        "success": "成功",
        "error": "错误",
        "confirm": "确认",
        "page_of": "/",
        "edit_text": "编辑文本",
        "new_text": "新建文本",
        "enter_text": "输入文本：",
        "find": "查找：",
        "replace_with": "替换为：",
        "replace_all": "全部替换",
        "no_match": "未找到匹配项",
        "matches_replaced": "已替换",
        "image_tools": "图片工具",
        "select_image": "选择图片",
        "move_image": "移动图片",
        "resize_image": "调整大小",
        "delete_image": "删除图片",
        "replace_image": "替换图片",
        "extract_image": "提取图片",
        "images": "图片",
        "no_images": "此页面无图片",
        "image_deleted": "图片已删除",
        "image_replaced": "图片已替换",
        "image_moved": "图片已移动",
        "select_image_first": "请先选择图片",
        "draft": "草稿",
        "confidential": "机密",
        "final": "最终版",
        "rejected": "已拒绝",
        "approved": "已批准",
        "urgent": "紧急",
        "draw_signature": "绘制签名",
        "clear": "清除",
        "insert_sig": "插入",
        "choose_stamp": "选择印章",
        "enter_watermark": "输入水印文本：",
        "total_pages": "总页数",
        "enter_page_range": "输入页面范围（例如：1,3,5-8）：",
        "extract": "提取",
        "split": "拆分",
        "merge": "合并",
        "rotation_degree": "旋转角度：",
        "rotate": "旋转",
        "file_saved": "文件已保存",
        "file_opened": "文件已打开",
        "changes_applied": "更改已应用",
        "editing_cancelled": "编辑已取消",
        "layers": "图层",
        "auto_saved": "自动保存",
        "recovery_found": "找到恢复文件。是否恢复？",
        "memory_usage": "内存使用",
    },
    "es": {"name": "Español", "dir": "ltr", "app_title": "Editor PDF Pro"},
    "fr": {"name": "Français", "dir": "ltr", "app_title": "Éditeur PDF Pro"},
    "de": {"name": "Deutsch", "dir": "ltr", "app_title": "PDF Editor Pro"},
    "ja": {"name": "日本語", "dir": "ltr", "app_title": "PDFエディタープロ"},
    "ko": {"name": "한국어", "dir": "ltr", "app_title": "PDF 편집기 Pro"},
    "pt": {"name": "Português", "dir": "ltr", "app_title": "Editor PDF Pro"},
}

# Fill missing translations with English defaults
for lang_code in LANGUAGES:
    if lang_code != "en":
        for key, value in LANGUAGES["en"].items():
            if key not in LANGUAGES[lang_code]:
                LANGUAGES[lang_code][key] = value


def get_text(lang: str, key: str) -> str:
    """Get translated text for a key"""
    if lang in LANGUAGES and key in LANGUAGES[lang]:
        return LANGUAGES[lang][key]
    return LANGUAGES["en"].get(key, key)


def get_available_languages() -> dict:
    """Get list of available languages"""
    return {code: data["name"] for code, data in LANGUAGES.items()}